name: Grid_Test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82651
title: Sanctus tests TheGrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#676767'
    - '#2c3441'
    - '#190f06'
    - '#aeb1d2'
    - '#fefefd'
  brandStrength: 0.15759982890449464
  lightness: 0.784094532718882
  saturation: 0.6875
  rhythmicContrast: 0.10962853068485856
purpose: []
