name: Grid_Test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82651
title: Sanctus tests TheGrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#292b1d'
    - '#4b5435'
    - '#7d9969'
    - '#f7e5bd'
  brandStrength: 0.15759982890449464
  lightness: 0.784094532718882
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
