name: Grid_Test
favicon: null
layout_spectrum: 0.50021
typography_spectrum: 0.82651
title: Sanctus tests TheGrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#464646'
    - '#333333'
    - '#808080'
    - '#1c1c1c'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
